### ISSUE TITLE
Blindbot crash on playlist link

### ISSUE THREAD

**Issue by Nico385412** [kindermoumoute/blindbot#1]
When i tried to give the first video of a playlist the bot crash
[https://www.youtube.com/watch?v=oA2xe8MgCuw&list=PLkLimRXN6NKxoP-Il39CIicFlV05OO3tJ&index=1](url)

UPDATE : If you try to reach this link you see that youtube rewrite the url and expose a /watch uri.

**Comment by kindermoumoute** [comment]
The issue is that right now everything after the "v=" is caught as the video id. It's an easy fix do you want to work on it?

**Comment by kindermoumoute** [comment]
Solved.
